version: '3.8'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./backend:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - app-network

  vue-app:
    image: node:20
    container_name: vue-app
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "8080:8080"
    networks:
      - app-network
    command: ["sh", "-c", "yarn install && yarn serve"]

networks:
  app-network:
    driver: bridge